# Generated by Django 2.1.4 on 2021-05-19 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_auto_20210518_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercicioss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('enunciado', models.CharField(max_length=99999)),
                ('resposta', models.CharField(max_length=99999)),
            ],
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('alunos', models.CharField(max_length=50)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercicioss',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.materia'),
        ),
    ]
