# Generated by Django 2.1.4 on 2021-05-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210518_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='alunos',
            field=models.CharField(max_length=100),
        ),
    ]
