# Generated by Django 2.1.4 on 2021-05-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210518_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='professor',
            field=models.IntegerField(),
        ),
    ]
