# Generated by Django 2.1.4 on 2021-05-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_exerciciossr'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
